# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_size_30', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('casing_size_30_status', models.PositiveSmallIntegerField(default=0)),
                ('casing_size_20', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('casing_size_20_status', models.PositiveSmallIntegerField(default=0)),
                ('casing_size_13_3by8', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('casing_size_13_3by8_status', models.PositiveSmallIntegerField(default=0)),
                ('casing_size_11_3by4', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('casing_size_11_3by4_status', models.PositiveSmallIntegerField(default=0)),
                ('casing_size_9_5by8', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('casing_size_9_5by8_status', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='DrainholeLiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liner_size_5', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('liner_size_5_status', models.PositiveSmallIntegerField(default=0)),
                ('liner_size_3_1by2', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('liner_size_3_1by2_status', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Liner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liner_size_7', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('liner_size_7_status', models.PositiveSmallIntegerField(default=0)),
                ('liner_size_5', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('liner_size_5_status', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.CharField(max_length=20)),
                ('platform_description', models.TextField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_complex_code', models.CharField(max_length=20)),
                ('process_complex_description', models.TextField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_name', models.CharField(max_length=50)),
                ('rig_description', models.TextField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_area', models.CharField(max_length=20)),
                ('well_code', models.CharField(max_length=20)),
                ('well_description', models.TextField(max_length=1024)),
                ('well_category', models.CharField(max_length=20)),
                ('well_jobtype', models.CharField(max_length=20)),
                ('well_layer', models.CharField(max_length=100)),
                ('well_remarks', models.TextField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Wellhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellhead_a_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_b_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_c_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_d_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_xmas_tree', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Well')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='process_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.ProcessComplex'),
        ),
        migrations.AddField(
            model_name='platform',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Rig'),
        ),
        migrations.AddField(
            model_name='liner',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Well'),
        ),
        migrations.AddField(
            model_name='drainholeliner',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Well'),
        ),
        migrations.AddField(
            model_name='casing',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promh.Well'),
        ),
    ]
