# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0002_auto_20160928_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='well_area',
            field=models.CharField(choices=[('MHS', 'MHS'), ('MHN', 'MHN')], max_length=10),
        ),
    ]
