# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0005_auto_20160928_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainholeliner',
            name='liner_size_3_1by2_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AlterField(
            model_name='drainholeliner',
            name='liner_size_5_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
    ]
