# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0008_auto_20160928_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellhead',
            name='wellhead_d_section',
        ),
        migrations.AddField(
            model_name='wellhead',
            name='wellhead_a_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='wellhead',
            name='wellhead_b_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='wellhead',
            name='wellhead_c_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='wellhead',
            name='wellhead_xmas_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
    ]
