# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0009_auto_20160928_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellhead',
            old_name='wellhead_xmas_section_status',
            new_name='wellhead_xmas_tree_status',
        ),
    ]
