# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:56
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0012_auto_20160929_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_size_30', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('casing_size_20', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('casing_size_13_3by8', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('casing_size_11_3by4', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('casing_size_9_5by8', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('liner_size_7', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('liner_size_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('liner_size_3_1by2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('wellhead_a_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_b_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_c_section', models.PositiveSmallIntegerField(default=0)),
                ('wellhead_xmas_tree', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_size_11_3by4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_size_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_size_30',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='drainholeliner',
            name='liner_size_3_1by2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='drainholeliner',
            name='liner_size_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='liner',
            name='liner_size_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='liner',
            name='liner_size_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
