# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0013_auto_20161003_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='liner_size_3_1by2',
            new_name='dh_liner_size_3_1by2',
        ),
        migrations.AddField(
            model_name='stock',
            name='dh_liner_size_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
