# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:37
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promh', '0014_auto_20161004_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='casing',
            name='well',
        ),
        migrations.RemoveField(
            model_name='drainholeliner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='drainholeliner',
            name='well',
        ),
        migrations.RemoveField(
            model_name='liner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liner',
            name='well',
        ),
        migrations.RemoveField(
            model_name='wellhead',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wellhead',
            name='well',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='casing_size_11_3by4',
            new_name='btc_9_5by8',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='dh_liner_size_3_1by2',
            new_name='btc_box_prem_pin_cross_over_9_5by8',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='dh_liner_size_5',
            new_name='btc_pin_prem_box_cross_over_9_5by8',
        ),
        migrations.AddField(
            model_name='stock',
            name='casing_size_18_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='chrome_casing_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='chrome_liner_hanger_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='chrome_liner_size_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_collar_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_collar_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_joint_11_3by4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_joint_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_joint_liner_11_3by4_large',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_shoe_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_shoe_size_18_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_shoe_size_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='float_shoe_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='liner_hanger_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='liner_hanger_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='prem_casing_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_box_prem_pin_cross_over_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_box_prem_pin_cross_over_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_pin_prem_box_cross_over_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='btc_pin_prem_box_cross_over_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_13_3by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_18_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_18_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_20_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_30',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_30_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_casing_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_casing_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_liner_hanger_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_liner_hanger_7_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_liner_size_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='chrome_liner_size_7_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_collar_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_collar_size_13_3by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_collar_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_collar_size_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_11_3by4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_11_3by4_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_liner_11_3by4_large',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_joint_liner_11_3by4_large_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_13_3by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_13_3by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_18_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_18_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_20_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='float_shoe_size_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_hanger_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_hanger_5_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_hanger_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_hanger_7_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_size_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_size_5_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_size_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='liner_size_7_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='prem_casing_9_5by8',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='well',
            name='prem_casing_9_5by8_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_a_section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_a_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_b_section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_b_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_c_section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_c_section_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_xmas_tree',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='well',
            name='wellhead_xmas_tree_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Required'), (1, 'In Use'), (2, 'Used Up')], default=0),
        ),
        migrations.DeleteModel(
            name='Casing',
        ),
        migrations.DeleteModel(
            name='DrainholeLiner',
        ),
        migrations.DeleteModel(
            name='Liner',
        ),
        migrations.DeleteModel(
            name='Wellhead',
        ),
    ]
